apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "receiver-profile.fullname" . }}
  labels:
    {{- include "receiver-profile.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "receiver-profile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "receiver-profile.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "receiver-profile.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.env.port }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: jwt_secret
            - name: DATABASEURL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: receiverprofiledburl
            - name: ACCESS_TOKEN_EXPIRY
              value: "{{ .Values.env.access_token_expiry }}"
            - name: REFRESH_TOKEN_EXPIRTY
              value: "{{ .Values.env.refresh_token_expiry }}"
            - name: AMQP_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: amqp_server_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: redisurl
            - name: ATTEMPTS
              value: "{{ .Values.env.attempts }}"
            - name: MIN_DELAY
              value: "{{ .Values.env.min_delay }}"
            - name: TIMES_CONNECTED
              value: "{{ .Values.env.times_connected }}"
            - name: TEMPLATE_BASE_URL
              value: {{ .Values.env.template_base_url }}
            - name: GA_USER_ACCOUNT_BASE_URL
              value: {{ .Values.env.ga_user_account_base_url }}
            - name: GET_API_KEY_END_URL
              value: {{ .Values.env.get_api_key_end_url }}
            - name: LOG_FILE_ENABLED
              value: "{{ .Values.env.log_file_enabled }}"
            - name: WEBHOOK_SECRET
              value: "{{ .Values.webhook_secret }}"
            - name: GINT_URL
              value: "{{ .Values.gint_url }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
