apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: telinfy
  namespace: telinfy-argo
spec:
  description: "Telinfy Main Project"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
