apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "message-status.fullname" . }}
  labels:
    {{- include "message-status.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "message-status.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "message-status.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "message-status.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.env.port }}"
            - name: DATABASEURL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: campaignmanagerdburl
            - name: CAMPAIGN_DATABASE_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: campaignmanagerdburl
            - name: CLOUD_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: cloudapidburl
            - name: CLOUD_DATABASE_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: cloudapidburl
            - name: USER_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: useraccountdburl
            - name: USER_DATABASE_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: useraccountdburl
            - name: SUBSCRIPTION_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: subscriptiondburl
            - name: ACCESS_TOKEN_EXPIRY
              value: "{{ .Values.env.access_token_expiry }}"
            - name: REFRESH_TOKEN_EXPIRTY
              value: "{{ .Values.env.refresh_token_expiry }}"
            - name: AMQP_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: amqp_server_url
            - name: GA_USER_ACCOUNT_BASE_URL
              value: {{ .Values.env.ga_user_account_base_url }}
            - name: GA_CLOUDAPI_INBOUND_SERVICE_BASE_URL
              value: {{ .Values.env.ga_cloudapi_inbound_service_base_url }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: redisurl
            - name: ATTEMPTS
              value: "{{ .Values.env.attempts }}"
            - name: MIN_DELAY
              value: "{{ .Values.env.min_delay }}"
            - name: TIMES_CONNECTED
              value: "{{ .Values.env.times_connected }}"
            - name: WHATSAPP_BUSINESS_END_URL
              value: {{ .Values.env.whatsapp_business_end_url }}
            - name: GET_USER_END_URL
              value: {{ .Values.env.get_user_end_url }}
            - name: GET_API_KEY_END_URL
              value: {{ .Values.env.get_api_key_end_url }}
            - name: GA_S3_ADAPTER_BASE_URL
              value: {{ .Values.env.ga_s3_adapter_base_url }}
            - name: MEDIA_DOWNLOAD_END_URL
              value: {{ .Values.env.media_download_end_url }}
            - name: GA_RECEIVER_PROFILE_BASE_URL
              value: {{ .Values.env.ga_receiver_profile_base_url }}
            - name: GRAPH_BASE_URL
              value: {{ .Values.env.graph_base_url }}
            - name: GRAPH_MESSAGE_END_URL
              value: {{ .Values.env.graph_message_end_url }}
            - name: GRAPH_TEMPLATE_END_URL
              value: {{ .Values.env.graph_template_end_url }}
            - name: GRAPH_PHONE_NUMBER_END_URL
              value: {{ .Values.env.graph_phone_number_end_url }}
            - name: CHATBOT_SESSION_EXPIRY_TIME
              value: "{{ .Values.env.chatbot_session_expiry_time }}"
            - name: AWS_ARN
              value: {{ .Values.env.s3_aws_arn }}
            - name: AWS_BUCKET_NAME
              value: {{ .Values.env.aws_bucket_name }}
            - name: AWS_BUCKET_REGION
              value: {{ .Values.env.aws_bucket_region }}
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: aws_access_key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: aws_secret_key
            - name: S3_FILE_BASE_URL
              value: {{ .Values.env.s3_file_base_url }}
            - name: MSG_BUCKET_SIZE
              value: "{{ .Values.env.msg_bucket_size }}"
            - name: CLOUD_ENABLED
              value: "{{ .Values.env.cloud_enabled }}"
            - name: GUPSHUP_ENABLED
              value: "{{ .Values.env.gupshup_enabled }}"
            - name: MESSAGE_LOAD_DISTRIBUTION_CRON
              value: "{{ .Values.env.message_load_distribution_cron }}"
            - name: MESSAGE_SCHEDULE_DISTRIBUTION_LOAD_CRON
              value: "{{ .Values.env.message_schedule_distribution_load_cron }}"
            - name: MESSAGE_STATUS_CHANNEL_PREFETCH
              value: "{{ .Values.env.message_status_channel_prefetch }}"
            - name: MESSAGE_STATUS_BULK_UPDATE_CHANNEL_PREFETCH
              value: "{{ .Values.env.message_status_bulk_update_channel_prefetch }}"
            - name: MQ_BATCH_SIZE
              value: "{{ .Values.env.mq_batch_size }}"
            - name: MESSAGE_STATUS_LOCK_CRON
              value: "{{ .Values.env.message_status_lock_cron }}"
            - name: CAMPAIGN_STATUS_FETCH_INTERVAL
              value: "{{ .Values.env.campaign_status_fetch_interval }}"
            - name: CAMPAIGN_MESSAGE_SENDING_INTERVAL
              value: "{{ .Values.env.campaign_message_sending_interval }}"
            - name: MESSAGE_STATUS_BULK_UPDATE_THRESHOLD
              value: "{{ .Values.env.message_status_bulk_update_threshold }}"
            - name: LOG_FILE_ENABLED
              value: "{{ .Values.env.log_file_enabled }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
