apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudapi-inbound.fullname" . }}
  labels:
    {{- include "cloudapi-inbound.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudapi-inbound.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudapi-inbound.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudapi-inbound.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.env.port }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: jwt_secret
            - name: DATABASEURL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: cloudapidburl
            - name: DATABASEURL_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: cloudapidburl
            - name: USER_RO_DATABASEURL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: useraccountdburl
            - name: CAMPAIGN_DATABASE_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: campaignmanagerdburl
            - name: SUBSCRIPTION_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: subscriptiondburl
            - name: SUBSCRIPTION_DATABASE_RO
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: subscriptiondburl
            - name: TELINFY_CAMPAIGN_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: telinfycampaigndburl
            - name: ACCESS_TOKEN_EXPIRY
              value: "{{ .Values.env.access_token_expiry }}"
            - name: REFRESH_TOKEN_EXPIRTY
              value: "{{ .Values.env.refresh_token_expiry }}"
            - name: AMQP_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: amqp_server_url
            - name: CAMPAIGN_MESSAGE_SENDING_INTERVAL
              value: "{{ .Values.env.campaign_message_sending_interval }}"
            - name: GA_USER_ACCOUNT_BASE_URL
              value: {{ .Values.env.ga_user_account_base_url }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: redisurl
            - name: ATTEMPTS
              value: "{{ .Values.env.attempts }}"
            - name: MIN_DELAY
              value: "{{ .Values.env.min_delay }}"
            - name: TIMES_CONNECTED
              value: "{{ .Values.env.times_connected }}"
            - name: WHATSAPP_BUSINESS_END_URL
              value: {{ .Values.env.whatsapp_business_end_url }}
            - name: GET_USER_END_URL
              value: {{ .Values.env.get_user_end_url }}
            - name: GET_CONTACT_END_URL
              value: {{ .Values.env.get_contact_end_url }}
            - name: GA_S3_ADAPTER_BASE_URL
              value: {{ .Values.env.ga_s3_adapter_base_url }}
            - name: MEDIA_DOWNLOAD_END_URL
              value: {{ .Values.env.media_download_end_url }}
            - name: GA_RECEIVER_PROFILE_BASE_URL
              value: {{ .Values.env.ga_receiver_profile_base_url }}
            - name: GRAPH_BASE_URL
              value: {{ .Values.env.graph_base_url }}
            - name: GRAPH_MESSAGE_END_URL
              value: {{ .Values.env.graph_message_end_url }}
            - name: GRAPH_TEMPLATE_END_URL
              value: {{ .Values.env.graph_template_end_url }}
            - name: GRAPH_PHONE_NUMBER_END_URL
              value: {{ .Values.env.graph_phone_number_end_url }}
            - name: GET_CUSTOMER_BLOCKED_CONTACTS_END_URL
              value: {{ .Values.env.get_customer_blocked_contacts_end_url }}
            - name: FIREBASE_TOKEN_THRESHOLD_IN_DAYS
              value: "{{ .Values.env.firebase_token_threshold_in_days }}"
            - name: CHATBOT_SESSION_EXPIRY_TIME_IN_SEC
              value: "{{ .Values.env.chatbot_session_expiry_time_in_sec }}"
            - name: CHATBOT_SESSION_EXPIRY_TIME_IN_MS
              value: "{{ .Values.env.chatbot_session_expiry_time_in_ms }}"
            - name: FCM_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: fcm_server_key
            - name: GA_CLOUDAPI_SERVICE_BASE_URL
              value: {{ .Values.env.ga_cloudapi_service_base_url }}
            - name: INTRCITY_WHATSAPP_BUSINESS_ID
              value: {{ .Values.env.intrcity_whatsapp_business_id }}
            - name: SEND_TEMPLATE_NOTIFICATION_URL
              value: {{ .Values.env.send_template_notification_url }}
            - name: EXAM_WINNER_WHATSAPP_BUSINESS_ID
              value: {{ .Values.env.exam_winner_whatsapp_business_id }}
            - name: CONVERSATION_ASSIGNED_TEMPLATE_NAME
              value: {{ .Values.env.conversation_assigned_template_name }}
            - name: CONVERSATION_ASSIGNED_TEMPLATE_LANGUAGE
              value: {{ .Values.env.conversation_assigned_template_language }}
            - name: BOT_TRANSLATION_ML
              value: {{ .Values.env.bot_translation_ml }}
            - name: FAVOURITE_HOMES_WHATSAPP_BUSINESS_ID
              value: {{ .Values.env.favourite_homes_whatsapp_business_id }}
            - name: MODERN_VET_WHATSAPP_BUSINESS_ACCOUNT
              value: {{ .Values.env.modern_vet_whatsapp_business_account }}
            - name: MODERN_VET_BOOK_NOW_KEYWORDS
              value: {{ .Values.env.modern_vet_book_now_keywords }}
            - name: MODERN_VET_SUPPORT_ALERT_KEYWORDS
              value: {{ .Values.env.modern_vet_support_alert_keywords }}
            - name: MODERN_VET_CLIENT_PHONE_NUMBERS
              value: {{ .Values.env.modern_vet_client_phone_numbers }}
            - name: MODERN_VET_NOTIFY_TEMPLATE_NAME
              value: {{ .Values.env.modern_vet_notify_template_name }}
            - name: MODERN_VET_NOTIFY_TEMPLATE_LANGUAGE
              value: {{ .Values.env.modern_vet_notify_template_language }}
            - name: FAVORITE_HOMES_CHANNEL_ID
              value: {{ .Values.env.favourite_homes_channel_id }}
            - name: FAVORITE_HOMES_HEADER_COOKIE
              value: {{ .Values.env.favourite_homes_header_cookie }}
            - name: INSTANCE_NAMESPACE
              value: {{ .Values.env.instance_namespace }}
            - name: CAMPAIGN_STATUS_FETCH_INTERVAL
              value: "{{ .Values.env.campaign_status_fetch_interval }}"
            - name: GOOGLE_SHEETS_RECEIVE_PREFETCH
              value: "{{ .Values.env.google_sheets_receive_prefetch }}"
            - name: LOG_FILE_ENABLED
              value: "{{ .Values.env.log_file_enabled }}"
            - name: INBOUND_RECEIVE_PREFETCH
              value: "{{ .Values.env.inbound_receive_prefetch }}"
            - name: VERIFY_TOKEN
              value: "{{ .Values.env.verify_token }}"
            - name: CENTRESQUARE_ACCOUNT_ID
              value: "{{ .Values.env.centresquare_account_id }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
